### ISSUE TITLE
Issues with the Positioning of Elements in the Banner

### ISSUE THREAD

**Issue by LauraWilson040** [LauraWilson040/components-on-a-grid#1]
I'm finding it difficult to move the ISS logo and my navigation menu to their proper spaces. Is it an issue with my code? Or am I did I forget to add in a property? @hellachella

![Screen Shot 2020-09-16 at 11 01 43 AM](https://user-images.githubusercontent.com/55108851/93356034-b6e55400-f80c-11ea-96d3-e6b1e4077240.png)
![Screen Shot 2020-09-16 at 11 01 54 AM](https://user-images.githubusercontent.com/55108851/93356035-b6e55400-f80c-11ea-9b3e-017ec84419dc.png)
![Screen Shot 2020-09-16 at 11 02 01 AM](https://user-images.githubusercontent.com/55108851/93356036-b77dea80-f80c-11ea-926f-1bbcbea4a416.png)

**Comment by hellachella** [comment]
Can you send me a screenshot of how it looks right now in the browser please?

**Comment by LauraWilson040** [comment]
Sorry, I just realized I forgot to tag you when I had posted this. Here's how it looks in Chrome. @hellachella
<img width="1680" alt="Screen Shot 2020-09-16 at 11 26 14 AM" src="https://user-images.githubusercontent.com/55108851/93358495-8e128e00-f80f-11ea-97ef-34d2a09c4cf5.png">
<img width="1680" alt="Screen Shot 2020-09-16 at 11 26 18 AM" src="https://user-images.githubusercontent.com/55108851/93358505-910d7e80-f80f-11ea-9a01-a80a515b7a30.png">
